version: '3.8'

services:
  app:
    build: .
    container_name: estabelecimentos-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=5000
